export const characterNames: Record<string, string> = {
  merlin: "Merlin",
  percival: "Percival",
  juniorMessenger: "Junior Messenger",
  troublemaker: "Troublemaker",
  cleric: "Cleric",
  seniorMessenger: "Senior Messenger",
  rogueGood: "Good Rogue",
  sorcererGood: "Good Sorcerer",
  lancelotGood: "Good Lancelot",
  untrustworthyServant: "Untrustworthy Servant",
  servant1: "Servant 1",
  servant2: "Servant 2",
  servant3: "Servant 3",
  morgana: "Morgana",
  oberon: "Oberon",
  mordred: "Mordred",
  lunatic: "Lunatic",
  sorcererEvil: "Evil Sorcerer",
  revealer: "Revealer",
  rogueEvil: "Evil Rogue",
  trickster: "Trickster",
  brute: "Brute",
  lancelotEvil: "Evil Lancelot",
  assassin: "Assassin",
  minion1: "Minion 1",
  minion2: "Minion 2",
  minion3: "Minion 3",
};
