import { Characters } from "types";

export const charactersDefault: Characters = {
  // Good Characters
  merlin: {
    id: "merlin",
    isActive: true,
    allegiance: "good",
    isOptional: false,
    description: [
      "Knows who is evil",
      "If assassinated, evil wins.",
      "Is a cool wizard",
      "Can do a backflip",
    ],
  },
  percival: {
    id: "percival",
    isActive: false,
    allegiance: "good",
    isOptional: true,
    description: [
      "Knows who Merlin is",
      "Sees both Merlin and Morgana, but is not sure who is who.",
      "Makes Good more powerful.",
    ],
  },
  cleric: {
    id: "cleric",
    isActive: false,
    allegiance: "good",
    isOptional: true,
    description: [
      "Knows if the leader of the first quest is good or evil.",
      "Makes Good more powerful..",
    ],
  },
  troublemaker: {
    id: "troublemaker",
    isActive: false,
    allegiance: "good",
    isOptional: true,
    description: [
      "Must lie when their loyaly is checked by the cleric or any rules/ability.",
      "Makes Evil more powerful.",
    ],
  },
  seniorMessenger: {
    id: "seniorMessenger",
    isActive: false,
    allegiance: "good",
    isOptional: true,
    description: [],
  },
  juniorMessenger: {
    id: "juniorMessenger",
    isActive: false,
    allegiance: "good",
    isOptional: true,
    description: [],
  },
  rogueGood: {
    id: "rogueGood",
    isActive: false,
    allegiance: "good",
    isOptional: true,
    description: [],
  },
  sorcererGood: {
    id: "sorcererGood",
    isActive: false,
    allegiance: "good",
    isOptional: true,
    description: [],
  },
  lancelotGood: {
    id: "lancelotGood",
    isActive: false,
    allegiance: "good",
    isOptional: true,
    description: [],
  },
  untrustworthyServant: {
    id: "untrustworthyServant",
    isActive: false,
    allegiance: "good",
    isOptional: true,
    description: [],
  },
  servant1: {
    id: "servant1",
    isActive: false,
    allegiance: "good",
    isOptional: true,
    description: ["Has no special powers"],
  },
  servant2: {
    id: "servant2",
    isActive: false,
    allegiance: "good",
    isOptional: true,
    description: ["Has no special powers"],
  },
  servant3: {
    id: "servant3",
    isActive: false,
    allegiance: "good",
    isOptional: true,
    description: ["Has no special powers"],
  },
  assassin: {
    id: "assassin",
    isActive: true,
    allegiance: "evil",
    isOptional: false,
    description: [
      "Can assasinate who they think is Merlin, at the end of the game.",
    ],
  },
  morgana: {
    id: "morgana",
    isActive: false,
    allegiance: "evil",
    isOptional: true,
    description: [
      "Disguises herself as Merlin",
      "Percival sees both Merlin and Morgana with their thumbs up.",
    ],
  },
  oberon: {
    id: "oberon",
    isActive: false,
    allegiance: "evil",
    isOptional: true,
    description: [
      "Does not reveal himself to other evil players.",
      "Makes Good more powerful.",
    ],
  },
  mordred: {
    id: "mordred",
    isActive: false,
    allegiance: "evil",
    isOptional: true,
    description: ["Makes evil more powerful."],
  },
  lunatic: {
    id: "lunatic",
    isActive: false,
    allegiance: "evil",
    isOptional: true,
    description: [
      "Must fail every quest they are on.",
      "Recommended for games with 7+ players.",
    ],
  },
  sorcererEvil: {
    id: "sorcererEvil",
    isActive: false,
    allegiance: "evil",
    isOptional: true,
    description: [],
  },
  revealer: {
    id: "revealer",
    isActive: false,
    allegiance: "evil",
    isOptional: true,
    description: [],
  },
  rogueEvil: {
    id: "rogueEvil",
    isActive: false,
    allegiance: "evil",
    isOptional: true,
    description: [],
  },
  trickster: {
    id: "trickster",
    isActive: false,
    allegiance: "evil",
    isOptional: true,
    description: ["Makes Evil more powerful."],
  },
  brute: {
    id: "brute",
    isActive: false,
    allegiance: "evil",
    isOptional: true,
    description: [
      "Makes good more powerful.",
      "May fail first three quests.",
      "Only allowed to fail the first 3 quests.",
    ],
  },
  lancelotEvil: {
    id: "lancelotEvil",
    isActive: false,
    allegiance: "evil",
    isOptional: true,
    description: [],
  },
  minion1: {
    id: "minion1",
    isActive: false,
    allegiance: "evil",
    isOptional: true,
    description: ["Has no special powers"],
  },
  minion2: {
    id: "minion2",
    isActive: false,
    allegiance: "evil",
    isOptional: true,
    description: ["Has no special powers"],
  },
  minion3: {
    id: "minion3",
    isActive: false,
    allegiance: "evil",
    isOptional: true,
    description: ["Has no special powers"],
  },
};

export const maxCharacters: Record<number, { good: number; evil: number }> = {
  5: {
    good: 3,
    evil: 2,
  },
  6: {
    good: 4,
    evil: 2,
  },
  7: {
    good: 4,
    evil: 3,
  },
  8: {
    good: 5,
    evil: 3,
  },
  9: {
    good: 6,
    evil: 3,
  },
  10: {
    good: 6,
    evil: 4,
  },
};

export const characterNames: Record<string, string> = {
  merlin: "Merlin",
  percival: "Percival",
  juniorMessenger: "Junior Messenger",
  troublemaker: "Troublemaker",
  cleric: "Cleric",
  seniorMessenger: "Senior Messenger",
  rogueGood: "Rogue",
  sorcererGood: "Sorcerer",
  lancelotGood: "Lancelot",
  untrustworthyServant: "Untrustworthy Servant",
  servant1: "Servant 1",
  servant2: "Servant 2",
  servant3: "Servant 3",
  morgana: "Morgana",
  oberon: "Oberon",
  mordred: "Mordred",
  lunatic: "Lunatic",
  sorcererEvil: "Sorcerer",
  revealer: "Revealer",
  rogueEvil: "Rogue",
  trickster: "Trickster",
  brute: "Brute",
  lancelotEvil: "Lancelot",
  assassin: "Assassin",
  minion1: "Minion 1",
  minion2: "Minion 2",
  minion3: "Minion 3",
};
