import { Characters } from "types/characters";
import { GameSession, Player } from "types/gameSession";
import { User } from "types/user";
import { generateUniqueId } from "utils/generateUniqueId";

export const userDefault = (): User => {
  return {
    id: generateUniqueId(),
    name: "",
    sessionId: null,
    imageUrl: "",
  };
};

export const playerDefault = (): Player => {
  return {
    id: "",
    name: "",
    characterId: "",
    isMyPlayerHost: false,
    joinedAt: 0,
    isReady: false,
  };
};

export const sessionDefault = (): GameSession => {
  return {
    id: "",
    name: "",
    players: {},
    numPlayers: 5,
    createdBy: "",
    step: "lobby",
    characters: [],
    isMyPlayerHostPlaying: true,
    numFailVotes: 0,
    numFailQuests: 0,
    isRitualFinished: false,
    activeQuestIndex: 0,
    quests: {
      0: {
        index: 0,
        status: "incomplete",
        numPlayers: 5,
        leaderId: "",
        players: [],
        votesToApprove: {},
        votesToSucceed: {},
        isApproved: false,
        isSuccessful: false,
      },
      1: {
        index: 1,
        status: "incomplete",
        numPlayers: 5,
        leaderId: "",
        players: [],
        votesToApprove: {},
        votesToSucceed: {},
        isApproved: false,
        isSuccessful: false,
      },
      2: {
        index: 2,
        status: "incomplete",
        numPlayers: 5,
        leaderId: "",
        players: [],
        votesToApprove: {},
        votesToSucceed: {},
        isApproved: false,
        isSuccessful: false,
      },
      3: {
        index: 3,
        status: "incomplete",
        numPlayers: 5,
        leaderId: "",
        players: [],
        votesToApprove: {},
        votesToSucceed: {},
        isApproved: false,
        isSuccessful: false,
      },
      4: {
        index: 4,
        status: "incomplete",
        numPlayers: 5,
        leaderId: "",
        players: [],
        votesToApprove: {},
        votesToSucceed: {},
        isApproved: false,
        isSuccessful: false,
      },
    },
  };
};

export const charactersDefault: Characters = {
  // Good Characters
  merlin: {
    id: "merlin",
    isActive: true,
    allegiance: "good",
    isOptional: false,
    description: ["Knows who is evil", "If assassinated, evil wins.", "Is a cool wizard", "Can do a backflip"],
    disabled: false,
  },
  percival: {
    id: "percival",
    isActive: false,
    allegiance: "good",
    isOptional: true,
    description: [
      "Knows who Merlin is",
      "Sees both Merlin and Morgana, but is not sure who is who.",
      "Makes Good more powerful.",
    ],
    disabled: false,
  },
  cleric: {
    id: "cleric",
    isActive: false,
    allegiance: "good",
    isOptional: true,
    description: ["Knows if the leader of the first quest is good or evil.", "Makes Good more powerful.."],
    disabled: false,
  },
  troublemaker: {
    id: "troublemaker",
    isActive: false,
    allegiance: "good",
    isOptional: true,
    description: [
      "Must lie when their loyaly is checked by the cleric or any rules/ability.",
      "Makes Evil more powerful.",
    ],
    disabled: false,
  },
  seniorMessenger: {
    id: "seniorMessenger",
    isActive: false,
    allegiance: "good",
    isOptional: true,
    description: [],
    disabled: true,
  },
  juniorMessenger: {
    id: "juniorMessenger",
    isActive: false,
    allegiance: "good",
    isOptional: true,
    description: [],
    disabled: true,
  },
  rogueGood: {
    id: "rogueGood",
    isActive: false,
    allegiance: "good",
    isOptional: true,
    description: [],
    disabled: false,
  },
  sorcererGood: {
    id: "sorcererGood",
    isActive: false,
    allegiance: "good",
    isOptional: true,
    description: [],
    disabled: false,
  },
  lancelotGood: {
    id: "lancelotGood",
    isActive: false,
    allegiance: "good",
    isOptional: true,
    description: [],
    disabled: false,
  },
  untrustworthyServant: {
    id: "untrustworthyServant",
    isActive: false,
    allegiance: "good",
    isOptional: true,
    description: [],
    disabled: false,
  },
  servant1: {
    id: "servant1",
    isActive: false,
    allegiance: "good",
    isOptional: true,
    description: ["Has no special powers"],
    disabled: false,
  },
  servant2: {
    id: "servant2",
    isActive: false,
    allegiance: "good",
    isOptional: true,
    description: ["Has no special powers"],
    disabled: false,
  },
  servant3: {
    id: "servant3",
    isActive: false,
    allegiance: "good",
    isOptional: true,
    description: ["Has no special powers"],
    disabled: false,
  },
  servant4: {
    id: "servant4",
    isActive: false,
    allegiance: "good",
    isOptional: true,
    description: ["Has no special powers"],
    disabled: false,
  },
  servant5: {
    id: "servant5",
    isActive: false,
    allegiance: "good",
    isOptional: true,
    description: ["Has no special powers"],
    disabled: false,
  },
  assassin: {
    id: "assassin",
    isActive: true,
    allegiance: "evil",
    isOptional: false,
    description: ["Can assasinate who they think is Merlin, at the end of the game."],
    disabled: false,
  },
  morgana: {
    id: "morgana",
    isActive: false,
    allegiance: "evil",
    isOptional: true,
    description: ["Disguises herself as Merlin", "Percival sees both Merlin and Morgana with their thumbs up."],
    disabled: false,
  },
  oberon: {
    id: "oberon",
    isActive: false,
    allegiance: "evil",
    isOptional: true,
    description: ["Does not reveal himself to other evil players.", "Makes Good more powerful."],
    disabled: false,
  },
  mordred: {
    id: "mordred",
    isActive: false,
    allegiance: "evil",
    isOptional: true,
    description: ["Makes evil more powerful."],
    disabled: false,
  },
  lunatic: {
    id: "lunatic",
    isActive: false,
    allegiance: "evil",
    isOptional: true,
    description: ["Must fail every quest they are on.", "Recommended for games with 7+ players."],
    disabled: false,
  },
  sorcererEvil: {
    id: "sorcererEvil",
    isActive: false,
    allegiance: "evil",
    isOptional: true,
    description: [],
    disabled: false,
  },
  revealer: {
    id: "revealer",
    isActive: false,
    allegiance: "evil",
    isOptional: true,
    description: [],
    disabled: true,
  },
  rogueEvil: {
    id: "rogueEvil",
    isActive: false,
    allegiance: "evil",
    isOptional: true,
    description: [],
    disabled: true,
  },
  trickster: {
    id: "trickster",
    isActive: false,
    allegiance: "evil",
    isOptional: true,
    description: ["Makes Evil more powerful."],
    disabled: true,
  },
  brute: {
    id: "brute",
    isActive: false,
    allegiance: "evil",
    isOptional: true,
    description: [
      "Makes good more powerful.",
      "May fail first three quests.",
      "Only allowed to fail the first 3 quests.",
    ],
    disabled: true,
  },
  lancelotEvil: {
    id: "lancelotEvil",
    isActive: false,
    allegiance: "evil",
    isOptional: true,
    description: [],
    disabled: true,
  },
  minion1: {
    id: "minion1",
    isActive: false,
    allegiance: "evil",
    isOptional: true,
    description: ["Has no special powers"],
    disabled: false,
  },
  minion2: {
    id: "minion2",
    isActive: false,
    allegiance: "evil",
    isOptional: true,
    description: ["Has no special powers"],
    disabled: false,
  },
  minion3: {
    id: "minion3",
    isActive: false,
    allegiance: "evil",
    isOptional: true,
    description: ["Has no special powers"],
    disabled: false,
  },
};
